#!/bin/bash

show_usage() {
    echo "usage: $(basename $0) [UUID=<UUID|generate>] [DEVICE=<device(hci0)>] [NOSCAN=<yes|no(yes)>] [MAJOR=<major version(5)>] [MINOR=<minor version(6)>] [CONNECTABLE=<yes/no(no)>] [INTERVAL=<from-to interval in ms(500-1000)>]"
    exit 1
}

syslog() {
    logger ${SYSLOG_OPTS} -t "$SYSLOG_TAG" "$@"
}

log() {
    syslog -p daemon.notice "$@" 2>&1
}

log_error() {
    syslog -p daemon.err "$@"
    exit 255
}

word() {
    printf "%02x %02x" $(($1 & 0xff)) $(($1 / 256))
}

byte() {
    printf "%02x" $(($1 & 0xff))
}

exec() {
    local CHECK_EXIT_CODE=$1
    shift
    if [ ${VERBOSE} -ne 0 ] ; then
        echo $@
        $@
    else
        $@ &> /dev/null
    fi
    if [ ${CHECK_EXIT_CODE} -ne 0 ] ; then
        local EXIT_CODE=$?
        if [ ${EXIT_CODE} -ne 0 ] ; then
            log_error "$@: Failed with exit code $EXIT_CODE"
        fi
    fi
}

VERBOSE=0
for ARG in $@ ; do
    if [ "$ARG" == "--verbose" ] || [ "$ARG" == "-v" ] ; then
        VERBOSE=1
    fi
done

SYSLOG_TAG="ble-ibeacon"
[ ${VERBOSE} -ne 0 ] && SYSLOG_OPTS="-s" || SYSLOG_OPTS=""
DEVICE=
CONNECTABLE=
CONFIG=
MAJOR=
MINOR=
NOSCAN=
INTERVAL=
TX_LEVEL=
if [ -f /etc/default/ble-ibeacon ] ; then
    . /etc/default/ble-ibeacon
elif [ -f /etc/sysconfig/ble-ibeacon ] ; then
    . /etc/sysconfig/ble-ibeacon
fi

UUID=$(echo ${UUID} | sed -e 's/[ -]//g')
if [ ${#UUID} -ne 32 ] ; then
    log_error "Invalid UUID: $UUID"
fi

TMP=""
for POS in $(seq 0 2 31) ; do
    TMP="$TMP${UUID:$POS:2} "
done
PP_UUID=${UUID:0:8}-${UUID:8:4}-${UUID:12:4}-${UUID:16:4}-${UUID:20}
UUID=${TMP^^:0:47}

if [ "$CONNECTABLE" == "yes" ] && [ "$CONNECTABLE" != "0" ] ; then
    TYPE=00
else
    TYPE=03
fi

case $1 in
    start)
        exec 1 hciconfig ${DEVICE} up
        hciconfig ${DEVICE} | grep -q " UP RUNNING"
        if [ $? -ne 1 ] ; then
            log_error "Device $DEVICE is not running"
        fi
        exec 1 hciconfig ${DEVICE} leadv 3
        if [ ${NOSCAN} == "yes" ] ; then
            exec 1 hciconfig ${DEVICE} noscan
        fi
        # LE Set Advertising Data
        exec 1 hcitool -i ${DEVICE} cmd 0x08 0x0008 \
            1E 02 01 1A 1A FF 4C 00 02 15 \
            ${UUID} \
            $(word ${MAJOR}) $(word ${MINOR}) \
            $(byte $((256 + ${TX_LEVEL})))
        # LE Set Advertising Parameters
        #exec 1 hcitool -i ${DEVICE} cmd 0x08 0x0006 $(word $(($INTERVAL_MIN * 1000 / 625))) $(word $(($INTERVAL_MAX * 1000 / 625))) ${TYPE} 00 00 00 00 00 00 00 00 07 00
        exec 1 hcitool -i ${DEVICE} cmd 0x08 0x0006 a0 00 a0 00 03 00 00 00 00 00 00 00 00 07 00
        # LE Set Advertise Enable
        exec 1 hcitool -i ${DEVICE} cmd 0x08 0x000a 01
        log "iBeacon $PP_UUID Major $MAJOR Minor $MINOR started on $DEVICE"
        ;;
    stop)
        log "iBeacon $PP_UUID Major $MAJOR Minor $MINOR stopped on $DEVICE"
        exec 0 hciconfig ${DEVICE} noleadv
        exec 0 hcitool -i ${DEVICE} cmd 0x08 0x000a 00
        ;;
    *)
        show_usage
        ;;
esac
